Added Gradle Support and Updated pom-DO-NOT-ACCEPT-PULL-REQUEST
WASdev/sample.javaee7.websocket pull request #2
Opened 2017-10-06 21:28 UTC by jjvilleg

2017-10-06 22:15 UTC, cthigh requested changes
This one is missing README.md updates

2017-10-11 18:46 UTC, cthigh approved these changes

2017-10-16 17:58 UTC, mattbsox approved these changes

2017-10-16 18:09 UTC, cthigh approved these changes

2017-10-16 18:09 UTC, cthigh commented on build.gradle
>          mavenLocal()
I think mavenLocal can be removed as well

2017-10-16 19:55 UTC, merged